export const categoryImage = {
  abenteuer: require("../assets/images/categories/abenteuer.jpg"),
  dating: require("../assets/images/categories/dating.jpg"),
  essen: require("../assets/images/categories/essen.jpg"),
  kreativ: require("../assets/images/categories/kreativ.jpg"),
  kultur: require("../assets/images/categories/kultur.jpg"),
  lernen: require("../assets/images/categories/lernen.jpg"),
  party: require("../assets/images/categories/party.jpg"),
  schach: require("../assets/images/categories/schach.jpg"),
  sport: require("../assets/images/categories/sport.jpg"),
  stadtdortmund: require("../assets/images/categories/stadtdortmund.jpg"),
  // TODO: Add images to assets folder
  //   politik: require("../assets/images/categories/politik.jpg"),
  //   eltern: require("../assets/images/categories/eltern.jpg"),
  //   haustiere: require("../assets/images/categories/haustiere.jpg"),
  //   sprache: require("../assets/images/categories/sprache.jpg"),
  //   hobbies: require("../assets/images/categories/hobbies.jpg"),
  //   karriere: require("../assets/images/categories/karriere.jpg"),
  //   kunst: require("../assets/images/categories/kunst.jpg"),
  //   outdoor: require("../assets/images/categories/outdoor.jpg"),
  //   religion: require("../assets/images/categories/religion.jpg"),
  //   soziales: require("../assets/images/categories/soziales.jpg"),
  //   spiele: require("../assets/images/categories/spiele.jpg"),
  //   fitness: require("../assets/images/categories/fitness.jpg"),
  //   tanzen: require("../assets/images/categories/tanzen.jpg"),
  //   tech: require("../assets/images/categories/tech.jpg"),
  //   bildung: require("../assets/images/categories/bildung.jpg"),
  //   wandern: require("../assets/images/categories/wandern.jpg"),
  //   radtour: require("../assets/images/categories/radtour.jpg"),
  //   "after-Work": require("../assets/images/categories/after-Work.jpg"),
  //   frühstück: require("../assets/images/categories/frühstück.jpg"),
  //   mittagessen: require("../assets/images/categories/mittagessen.jpg"),
  //   dinner: require("../assets/images/categories/dinner.jpg"),
  //   musik: require("../assets/images/categories/musik.jpg"),
  //   konzert: require("../assets/images/categories/konzert.jpg"),
  //   joggen: require("../assets/images/categories/joggen.jpg"),
  //   tennis: require("../assets/images/categories/tennis.jpg"),
  //   badminton: require("../assets/images/categories/badminton.jpg"),
  //   fußball: require("../assets/images/categories/fußball.jpg"),
  //   basketball: require("../assets/images/categories/basketball.jpg"),
  //   volleyball: require("../assets/images/categories/volleyball.jpg"),
  //   rudern: require("../assets/images/categories/rudern.jpg"),
  //   kampfsport: require("../assets/images/categories/kampfsport.jpg"),
  //   skaten: require("../assets/images/categories/skaten.jpg"),
  //   golf: require("../assets/images/categories/golf.jpg"),
  //   meditation: require("../assets/images/categories/meditation.jpg"),
  //   lgbtq: require("../assets/images/categories/lgbtq.jpg"),
  //   kino: require("../assets/images/categories/kino.jpg"),
  //   ausflug: require("../assets/images/categories/ausflug.jpg"),
  //   ausstellung: require("../assets/images/categories/ausstellung.jpg"),
  //   fotografie: require("../assets/images/categories/fotografie.jpg"),
  //   brettspiele: require("../assets/images/categories/brettspiele.jpg"),
};
