// https://de.wikipedia.org/wiki/Liste_der_Gro%C3%9Fst%C3%A4dte_in_Deutschland

export const cities = [
  "Berlin",
  "Hamburg",
  "München",
  "Köln",
  "Frankfurt am Main",
  "Stuttgart",
  "Düsseldorf",
  "Leipzig",
  "Dortmund",
  "Essen",
  "Bremen",
  "Dresden",
  "Hannover",
  "Nürnberg",
  "Duisburg",
  "Bochum",
  "Wuppertal",
  "Bielefeld",
  "Bonn",
  "Münster",
  "Mannheim",
  "Karlsruhe",
  "Augsburg",
  "Wiesbaden",
  "Mönchengladbach",
  "Gelsenkirchen",
  "Aachen",
  "Braunschweig",
  "Kiel",
  "Chemnitz",
  "Halle (Saale)",
  "Magdeburg",
  "Freiburg",
  "Krefeld",
  "Mainz",
  "Lübeck",
  "Erfurt",
  "Oberhause",
  "Rostock",
  "Kassel",
  "Hagen",
  "Potsdam",
  "Saarbrücken",
  "Hamm",
  "Ludwigshafen am Rhein",
  "Mülheim an der Ruhr",
  "Oldenburg (Oldb)",
  "Osnabrück",
  "Leverkusen",
  "Darmstadt",
  "Heidelberg",
  "Solingen",
  "Herne",
  "Regensburg",
  "Neuss",
  "Paderborn",
  "Ingolstadt",
  "Offenbach am Main",
  "Fürth",
  "Würzburg",
  "Ulm",
  "Heilbronn",
  "Pforzheim",
  "Wolfsburg",
  "Bottrop",
  "Göttingen",
  "Reutlingen",
  "Koblenz",
  "Erlangen",
  "Bremerhaven",
  "Remscheid",
  "Bergisch Gladbach",
  "Recklinghausen",
  "Trier",
  "Jena",
  "Moers",
  "Salzgitter",
  "Siegen",
  "Gütersloh",
  "Hildesheim",
];
